# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:40
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('phoneNumbers', jsonfield.fields.JSONField(default=api.models.Person.phone_number_default, verbose_name='PhoneNumber')),
                ('emailAddresses', jsonfield.fields.JSONField(default=api.models.Person.email_address_default, verbose_name='EmailAddress')),
                ('addresses', jsonfield.fields.JSONField(default=api.models.Person.address_default, verbose_name='Address')),
            ],
        ),
    ]
